### PR TITLE
Docs/azure ad oauth

### PR DESCRIPTION
**Pull request by nbarlowATI**
* Fix one typo in `deployments/azure_ad_auth_spawn_aml_with_userspaces/jupyterhub_config.py` in the string formatting for oauth_callback_url.

* Expand on the AD authentication section in the README (particularly for when testing locally, using ngrok)

### CODE REVIEW

**Comment by tam203** [comment]
Ahhh, this doc's work is marvellous. 🙏

 Not sure I understand the `InteractiveLoginAuthentication` so lets discuss later!

**Comment by tam203** [comment]
On the clean up of the configs I think that:

```
# Class for authenticating users.

import os
import json
import jwt
import os
import urllib

from tornado.auth import OAuth2Mixin
from tornado.log import app_log
from tornado.httpclient import HTTPRequest, AsyncHTTPClient

from jupyterhub.auth import LocalAuthenticator
from traitlets import Unicode, default
from oauthenticator.azuread import AzureAdOAuthenticator

class AzureAdOAuthenticatorProxy(AzureAdOAuthenticator):
    """
    Custom Authenticator to use Azure AD with JupyterHub.
    This class is just a copy of the AzureAdOAuthenticator
    It's only here for easier debugging whilst I try figure out
    how to use the deligated permissions to act as the signed in user.
    """

    login_service = Unicode(
        os.environ.get('LOGIN_SERVICE', 'Azure AD'),
        config=True,
        help="""Azure AD domain name string, e.g. My College"""
    )

    tenant_id = Unicode(config=True, help="The Azure Active Directory Tenant ID")

    @default('tenant_id')
    def _tenant_id_default(self):
        return os.environ.get('AAD_TENANT_ID', '')

    username_claim = Unicode(config=True)

    @default('username_claim')
    def _username_claim_default(self):
        return 'name'

    @default("authorize_url")
    def _authorize_url_default(self):
        return 'https://login.microsoftonline.com/{0}/oauth2/authorize'.format(self.tenant_id)

    @default("token_url")
    def _token_url_default(self):
        return 'https://login.microsoftonline.com/{0}/oauth2/token'.format(self.tenant_id)

    async def authenticate(self, handler, data=None):
        code = handler.get_argument("code")
        http_client = AsyncHTTPClient()

        params = dict(
            client_id=self.client_id,
            client_secret=self.client_secret,
            grant_type='authorization_code',
            code=code,
            redirect_uri=self.get_callback_url(handler))

        data = urllib.parse.urlencode(
            params, doseq=True, encoding='utf-8', safe='=')

        url = self.token_url

        headers = {
            'Content-Type':
            'application/x-www-form-urlencoded; charset=UTF-8'
        }
        req = HTTPRequest(
            url,
            method="POST",
            headers=headers,
            body=data  # Body is required for a POST...
        )

        resp = await http_client.fetch(req)
        resp_json = json.loads(resp.body.decode('utf8', 'replace'))

        # app_log.info("Response %s", resp_json)
        access_token = resp_json['access_token']

        id_token = resp_json['id_token']
        decoded = jwt.decode(id_token, verify=False)

        userdict = {"name": decoded[self.username_claim]}
        userdict["auth_state"] = auth_state = {}
        auth_state['access_token'] = access_token
        # results in a decoded JWT for the user data
        auth_state['user'] = decoded

        return userdict


c.JupyterHub.authenticator_class = AzureAdOAuthenticatorProxy
```

should all go from `/aml-jupyterhub/deployments/azure_ad_auth_spawn_aml_with_userspaces/jupyterhub_config.py`

and replace with:

```
from oauthenticator.azuread import AzureAdOAuthenticator
c.JupyterHub.authenticator_class = AzureAdOAuthenticator
```

**Comment by nbarlowATI** [comment]
Thanks!  I just implemented this suggestion - do use the AzureAdOAuthenticator directly and it works fine :)
One possible drawback to this though is that the `auth_state` dictionary apparently has some useful info (e.g. "objectId") for the 'create-on-behalf-of' process.   Probably it's possible to access this dictionary some other way though...

For the ```InteractiveLoginAuthentication```, this was the easiest way I found to specify the Tenant ID.  Without this, I would get the "Device Login", and then after that another interactive login to create the workspace, which then told me I wasn't allowed to access that subscription (because it was using the wrong tenant_id).   With this InteractiveLoginAuthentication, the behaviour was exactly the same, except that since it knew which tenant_id to use, it worked.   
TBF I haven't tried running without this when using the AD login to Jupyterhub.  Possibly it wouldn't be needed then.  And similarly, if the Service Principal is going to create resources on behalf of the user, it might not be needed for that either.
I will investigate further...

**Comment by tam203** [comment]
@nbarlowATI @pierocor - I'm happy for you to merge this.

@nbarlowATI- One suggestion is maybe to mention where to find the Tenant ID in the Azure portal. I realise this could (and should) apply to all the env vars but since this is a new one it might be best to set an example. Either in a setup section or a section specifically about the env vars.

@nbarlowATI @pierocor  - More generally since you guys are the main developers on this at the moment don't feel you need to wait for me to approve pull requests, feel free to review and merge between yourself. I like so see what's going on but don't let me hold you up or make things confusing with multiple parallel branches because I'm not merging/responding quick enough.

**Comment by nbarlowATI** [comment]
OK sounds good!  I added a new markdown file environmentvars.md with some explanations of the variables in `.env` and how to find them, and linked from the README.   
Will merge the PR after another quick proof-read...

**Comment by tam203** [comment]
👏 👏 👏  @nbarlowATI

**Pull request merged**
